### ISSUE TITLE
Remove no longer use maven repo cache builder

### ISSUE THREAD

**Issue by psiroky** [kiegroup/kie-build-helper-jenkins-plugin#13]
The Maven repo cache builder (https://github.com/kiegroup/kie-build-helper-jenkins-plugin/blob/master/src/main/java/org/kie/jenkinsci/plugins/kieprbuildshelper/MavenRepoCacheBuilder.java) is no longer used and should be removed.

**Comment by AntStephenson** [comment]
@psiroky I'm wondering if we should update: https://github.com/kiegroup/kie-build-helper-jenkins-plugin/blob/master/README.adoc#2-available-extension-points

... and remove section 2,1?

**Comment by psiroky** [comment]
Yes, please update the README as well.

**Comment by AntStephenson** [comment]
Resolved by #15
