### ISSUE TITLE
Create PR job to test changes before merging

### ISSUE THREAD

**Issue by psiroky** [kiegroup/kie-build-helper-jenkins-plugin#16]

**Comment by pszubiak** [comment]
@psiroky do you think that this job should be part of system view? Or better is to put it to PRs or other view?

**Comment by pszubiak** [comment]
@psiroky if you don't mind first I'll configure this job manually and then write DSL for it.

**Comment by AntStephenson** [comment]
@pszubiak creating this manually initially makes sense

**Comment by psiroky** [comment]
I don't think it should be part of system view. That view is used to store jobs related to the system configuration/management like the slaves images, etc. I would just put it in the PRs view.

Yes, creating is manually sounds good.
