### ISSUE TITLE
Extract branch configuration to an external location

### ISSUE THREAD

**Issue by mcimbora** [kiegroup/kie-build-helper-jenkins-plugin#6]
@psiroky @mbiarnes The branch configuration is currently hardcoded in the code (see https://github.com/kiegroup/kie-build-helper-jenkins-plugin/blob/master/src/main/java/org/kie/jenkinsci/plugins/kieprbuildshelper/KieRepositoryLists.java). It would be nice to move it to an external location (e.g. properties file, env variables...) so that a new build is not required with each branch version bump.

**Comment by psiroky** [comment]
Yes, I am in the middle of doing this, but it's not yet finished. The branch config will be stored in this file and the plugin will read it from there every time https://github.com/kiegroup/droolsjbpm-build-bootstrap/blob/master/script/branch-mapping.yaml

**Comment by psiroky** [comment]
See #7
